from tests.mixed_walk_test import test_time_walker_multi, mixed_walk

# debugging: gdb --args python -m tests.test

if __name__ == "__main__":
    mixed_walk()
    #test_time_walker_multi()
    # corr(7, 16, 300)
    # benchmark_brownian(200)
    # mixed_walk()
    # test_time_walk()
    # test_weather()
    # corr(7, 16, 300)
    # print("Running tests...")
    """
        test_time_walker()
        test_time_walker_multi()
        test_biased_walk()
        test_brownian_wrapper()
        test()
        test_mixed_walk_time()
        # move_bank_test()
        landcover_test()
        test_brownian_wrapper()
        movebank_test()
        test_terrain_correlated()
        test_mixed_walk_time()
        corr_simple(12)
        corr_simple(16)
        corr_simple(20)
        corr_simple(24)
        test_terrain()
        mixed_walk()
        test_terrain_correlated()
        corr()
        corr_movebank_test()
        movebank_test()
        test_brownian_wrapper()
        """
# benchmark_brownian(200)
